[context.production.environment]
HUGO_VERSION = "0.46"

[context.deploy-preview.environment]
HUGO_VERSION = "0.46"

[build]
publish = "public"
command = "gulp sass && hugo"

[[redirects]]
  from = "/downloads"
  to = "/wallets"
  status = 301
  force = true


[[redirects]]
  from = "/navpay"
  to = "https://navhub.org/projects/nav-pay"
  status = 301
  force = true
